# Generated by Django 3.2.8 on 2022-01-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Účet', 'verbose_name_plural': 'Účty'},
        ),
    ]
