# Generated by Django 3.2.8 on 2022-01-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('aaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaaaaaaaa'),), 'verbose_name': 'Účet', 'verbose_name_plural': 'Účty'},
        ),
    ]
