# Generated by Django 3.2.10 on 2022-12-20 20:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, validators=[accounts.models.barcode_validator]),
        ),
    ]
