# Generated by Django 3.2.8 on 2021-11-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('TRACE', 'Trace'), ('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], max_length=10)),
                ('app', models.CharField(choices=[('REPACKING', 'Repacking'), ('USER_MANAGMENT', 'User Managment'), ('MAIL_REPORTS', 'Mail Reports'), ('LOGGING', 'Logging')], max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
