# Generated by Django 3.2.8 on 2021-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='app',
            field=models.CharField(choices=[('REPACKING', 'Repacking'), ('USER_MANAGMENT', 'User Managment'), ('MAIL_REPORTS', 'Mail Reports'), ('LOGGING', 'Logging')], max_length=15),
        ),
    ]
