# Generated by Django 3.2.8 on 2022-01-18 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0003_alter_log_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Čas'),
        ),
        migrations.AlterField(
            model_name='log',
            name='app',
            field=models.CharField(choices=[('Prebaľovanie', 'Repacking'), ('Správa používateľov', 'User Managment'), ('Posielanie mailov', 'Mail Reports'), ('logovanie', 'Logging')], max_length=25, verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='log',
            name='priority',
            field=models.CharField(choices=[('TRACE', 'Trace'), ('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], max_length=10, verbose_name='Priorita'),
        ),
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
    ]
