# Generated by Django 3.2.8 on 2022-01-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20220118_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'permissions': (('bla', 'Bla Bla'),), 'verbose_name': 'Log', 'verbose_name_plural': 'Logy'},
        ),
    ]
