# Generated by Django 3.2.8 on 2022-01-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_log_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Log', 'verbose_name_plural': 'Logy'},
        ),
    ]
