# Generated by Django 3.2.8 on 2022-01-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsendsetting',
            options={'verbose_name': 'Mailová adresa', 'verbose_name_plural': 'Mailové adresy'},
        ),
    ]
