# Generated by Django 3.2.8 on 2021-12-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='barcode_number',
            new_name='barcode',
        ),
    ]
