# Generated by Django 3.2.8 on 2021-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repacking_standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU_code', models.CharField(max_length=50)),
                ('COFOR_code', models.CharField(max_length=50)),
                ('datetime_of_create', models.DateTimeField(auto_now=True)),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
