# Generated by Django 3.2.8 on 2021-10-29 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repacking_standard',
            name='boxes_on_pallet_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='boxes_on_pallet_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='destination',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='package_type_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='package_type_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='pcs_on_pallet_im',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='pcs_on_pallet_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='pcs_package_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='pcs_package_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='pcs_per_move',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='remark',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='repacking_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='repacking_standard',
            name='supplier',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='repacking_standard',
            name='COFOR_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='repacking_standard',
            name='SKU_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='repacking_standard',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
