# Generated by Django 3.2.8 on 2021-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_count_of_boxes_on_pallet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_count_of_items_in_package',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_count_of_items_on_pallet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='items_per_move',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_count_of_boxes_on_pallet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_count_of_items_in_package',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_count_of_items_on_pallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
