# Generated by Django 3.2.8 on 2022-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0002_auto_20211210_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Fotka', 'verbose_name_plural': 'Fotky'},
        ),
        migrations.AlterModelOptions(
            name='repackhistory',
            options={'verbose_name': 'Prebaľovanie', 'verbose_name_plural': 'Prebaľovania'},
        ),
        migrations.AlterModelOptions(
            name='repackingstandard',
            options={'verbose_name': 'Štandard', 'verbose_name_plural': 'Štandardy'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'OPP', 'verbose_name_plural': 'OPP'},
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='unit_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
