# Generated by Django 3.2.8 on 2021-10-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0002_auto_20211029_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='repacking_standard',
            new_name='RepackingStandard',
        ),
        migrations.CreateModel(
            name='Repack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repack_datetime', models.DateTimeField(auto_now=True)),
                ('idp', models.CharField(max_length=50)),
                ('repacking_standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repacking.repackingstandard')),
            ],
        ),
    ]
