# Generated by Django 3.2.8 on 2022-01-18 08:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repacking', '0003_auto_20220117_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackhistory',
            name='idp',
            field=models.CharField(max_length=50, verbose_name='IDP'),
        ),
        migrations.AlterField(
            model_name='repackhistory',
            name='repack_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Trvanie prebalu'),
        ),
        migrations.AlterField(
            model_name='repackhistory',
            name='repack_finish',
            field=models.DateTimeField(verbose_name='Konies prebalu'),
        ),
        migrations.AlterField(
            model_name='repackhistory',
            name='repack_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Začiatok prebalu'),
        ),
        migrations.AlterField(
            model_name='repackhistory',
            name='repacking_standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repacking_standard', to='repacking.repackingstandard', verbose_name='Štandard'),
        ),
        migrations.AlterField(
            model_name='repackhistory',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Prebaľovali používatelia'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='COFOR',
            field=models.CharField(default='', max_length=50, verbose_name='COFOR'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='SKU',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Vytvoril používateľ'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='destination',
            field=models.CharField(default='', max_length=50, verbose_name='Destinácia'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_count_of_boxes_on_pallet',
            field=models.PositiveIntegerField(default=0, verbose_name='Boxov na vstupnej palete'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_count_of_items_in_package',
            field=models.PositiveIntegerField(default=0, verbose_name='KS vo vstupnom balení'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_count_of_items_on_pallet',
            field=models.PositiveIntegerField(default=0, verbose_name='KS na vstupnej palete'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_photos',
            field=models.ManyToManyField(blank=True, related_name='input_photos', to='repacking.Photos', verbose_name='Fotky vstupného obalu'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_type_of_package',
            field=models.CharField(default='', max_length=50, verbose_name='Druh vstupného obalu'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='instructions',
            field=models.CharField(default='', max_length=1200, verbose_name='Inštrukcie'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='items_per_move',
            field=models.PositiveIntegerField(default=0, verbose_name='kusov na pohyb'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_count_of_boxes_on_pallet',
            field=models.PositiveIntegerField(default=0, verbose_name='Boxov na výstupnej palete'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_count_of_items_in_package',
            field=models.PositiveIntegerField(default=0, verbose_name='KS vo výstupnom balení'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_count_of_items_on_pallet',
            field=models.PositiveIntegerField(default=0, verbose_name='KS na výstupnej palete'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_photos',
            field=models.ManyToManyField(blank=True, related_name='output_photos', to='repacking.Photos', verbose_name='Fotky výstupného obalu'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_type_of_package',
            field=models.CharField(default='', max_length=50, verbose_name='Druh výstupného obalu'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='repacking_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Doba prebalu'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='supplier',
            field=models.CharField(default='', max_length=50, verbose_name='Dodávateľ'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='tools', to='repacking.Tools', verbose_name='OPP'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='unit_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Jednotková váha'),
        ),
    ]
