# Generated by Django 3.2.8 on 2021-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0003_auto_20211029_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repackingstandard',
            old_name='pcs_on_pallet_im',
            new_name='pcs_on_pallet_in',
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='package_type_in',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='package_type_out',
            field=models.CharField(default='', max_length=50),
        ),
    ]
