# Generated by Django 3.2.8 on 2021-10-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0004_auto_20211029_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackingstandard',
            name='unit_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
