# Generated by Django 3.2.10 on 2022-12-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0005_auto_20220118_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackingstandard',
            name='SKU',
            field=models.CharField(default='', max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='unit_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Jednotková váha'),
        ),
        migrations.AlterUniqueTogether(
            name='repackingstandard',
            unique_together={('SKU', 'destination')},
        ),
    ]
