# Generated by Django 3.2.8 on 2021-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0005_alter_repackingstandard_unit_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackingstandard',
            name='SKU_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
