# Generated by Django 3.2.8 on 2021-11-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repacking', '0006_alter_repackingstandard_sku_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repack_datetime', models.DateTimeField(auto_now=True)),
                ('idp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='repackingstandard',
            old_name='COFOR_code',
            new_name='COFOR',
        ),
        migrations.RenameField(
            model_name='repackingstandard',
            old_name='SKU_code',
            new_name='SKU',
        ),
        migrations.AddField(
            model_name='repackingstandard',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Repack',
        ),
        migrations.AddField(
            model_name='repackhistory',
            name='creator',
            field=models.ManyToManyField(to='repacking.RepackingStandard'),
        ),
        migrations.AddField(
            model_name='repackhistory',
            name='repacking_standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repacking_standard', to='repacking.repackingstandard'),
        ),
    ]
