# Generated by Django 3.2.8 on 2021-11-16 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repacking', '0007_auto_20211116_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repackhistory',
            name='creator',
        ),
        migrations.AddField(
            model_name='repackhistory',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
