# Generated by Django 3.2.8 on 2021-11-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0008_auto_20211116_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tools')),
            ],
        ),
        migrations.AddField(
            model_name='repackingstandard',
            name='input_photos',
            field=models.ManyToManyField(related_name='input_photos', to='repacking.Tools'),
        ),
        migrations.AddField(
            model_name='repackingstandard',
            name='output_photos',
            field=models.ManyToManyField(related_name='output_photos', to='repacking.Tools'),
        ),
        migrations.AddField(
            model_name='repackingstandard',
            name='tools',
            field=models.ManyToManyField(related_name='tools', to='repacking.Tools'),
        ),
    ]
