# Generated by Django 3.2.8 on 2021-11-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0009_auto_20211116_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_photos',
            field=models.ManyToManyField(blank=True, related_name='input_photos', to='repacking.Tools'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_photos',
            field=models.ManyToManyField(blank=True, related_name='output_photos', to='repacking.Tools'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='tools', to='repacking.Tools'),
        ),
    ]
