# Generated by Django 3.2.8 on 2021-11-16 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0010_auto_20211116_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repackhistory',
            old_name='repack_datetime',
            new_name='repack_finish',
        ),
        migrations.AddField(
            model_name='repackhistory',
            name='repack_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='repackhistory',
            name='repack_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
