# Generated by Django 3.2.8 on 2021-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0011_auto_20211116_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackhistory',
            name='repack_finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='input_photos',
            field=models.ManyToManyField(blank=True, related_name='input_photos', to='repacking.Photos'),
        ),
        migrations.AlterField(
            model_name='repackingstandard',
            name='output_photos',
            field=models.ManyToManyField(blank=True, related_name='output_photos', to='repacking.Photos'),
        ),
    ]
