# Generated by Django 3.2.8 on 2021-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repacking', '0012_auto_20211202_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='photo',
            field=models.ImageField(upload_to='tools/%Y/%m/'),
        ),
    ]
