# Generated by Django 3.2.8 on 2021-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('repacking', '0013_auto_20211209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repackhistory',
            name='users',
            field=models.ManyToManyField(related_name='users', to='employees.Employee'),
        ),
    ]
